# -*- coding: utf-8 -*-
"""02 003 Ejercicio 7 Modulo 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pM8d0BvrrA34rnvUNGPTYkZsvBQWlSYs
"""

# 7.- Sube a un repositorio de git hub un programa que encuentre un intervalo que tenga 73 números no primos seguidos y compártelo a través de su link en Git Hub.

def is_prime (y):
  for i in range(2,y):
   if y%i ==0:
      result = False
      break
  if y == i + 1:
    result = True
  return result
contador = 0
last_no_prime = 1
next_number = 2
list_not_prime =[]

while contador<73:
  next_number =next_number + 1
  if not is_prime (next_number):
    contador = contador + 1
    list_not_prime.append(next_number)
  else:
    contador=0
    list_not_prime =[]
print(list_not_prime)